[package]
name = "flownet-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "flownet-cli"
path = "main.rs"

[lib]
name = "flownet_core"
path = "lib.rs"

[dependencies]
pcap = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
etherparse = "0.13"
chrono = { version = "0.4", features = ["serde"] }
dialoguer = "0.11"
ctrlc = "3.4"
